### ISSUE TITLE
http_response is putting a CRLF between status code and status text

### ISSUE THREAD

**Issue by mascarenhas** [jsimmons/mongrel2-lua#2]
Title says it all. :-) Per HTTP spec the status code and status text is separated by just a space, not CRLF. Just remove the extra CRLF from HTTP_FORMAT and everything is ok.

**Comment by jsimmons** [comment]
Correcting HTTP_FORMAT
Closed by a9e88336a3c5beaee3b95a45523ad127deda2715

**Comment by jsimmons** [comment]
Fixed by a9e8833
