### ISSUE TITLE
Error in SQL query, patch attached.

### ISSUE THREAD

**Issue by zedshaw** [jsimmons/mongrel2-lua#3]
Hey josh, there's a 1 line fix for the m2 config stuff that is breaking configs with multiple hosts:

<pre>
diff --git a/config.lua b/config.lua
index d535b18..8e219f0 100644
--- a/config.lua
+++ b/config.lua
@@ -67,7 +67,7 @@ end
 local function db_select(db, name, predicate)
     local query
 
-    if data then
+    if predicate then
         local conditions = {}
         for k, v in pairs(predicate) do
             local condition = ('%s = %s'):format(k, sql_tostring(v))
</pre>

Thanks.

**Comment by jsimmons** [comment]
Ah that was clever...
Fixed at head.
