### ISSUE TITLE
Required ZeroMQ version should be bumped to 2.1.4

### ISSUE THREAD

**Issue by mtowers** [jsimmons/mongrel2-lua#8]
When Mongrel2 drops release 1.6, the required version of ZeroMQ should be updated to 2.1.4+.  Note that 2.1.6 should not be used due to a known bug (https://github.com/zeromq/libzmq/issues/206).  At the time of this writing 2.1.7 has _not_ been tested with Mongrel2.

**Comment by jsimmons** [comment]
The issue was supposedly fixed against master for 2.1.6, I've been running mongrel2 off trunk zmq. I'll investigate further and bump the requirements.

**Comment by jsimmons** [comment]
Fixed
